app.db.url: jdbc:hsqldb:mem:data-compliance-db;sql.syntax_pgs=true;shutdown=false

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
