spring:

  application:
    name: dps-data-compliance

  security:
    oauth2:
      client:
        registration:
          dps-data-compliance:
            provider: hmpps-auth
            client-id: ${dps.data.compliance.client.id}
            client-secret: ${dps.data.compliance.client.secret}
            authorization-grant-type: client_credentials
        provider:
          hmpps-auth:
            token-uri: ${hmpps.auth.base.url}/oauth/token

  flyway.locations: classpath:db/migration,classpath:db/quartz

  datasource:
    url: ${app.db.url}
    username: sa
    password:
    continueOnError: true

    hikari:
      pool-name: DPS-Data-Compliance-CP
      connectionTimeout: 1000
      validationTimeout:  500

  quartz:
    job-store-type: jdbc
    properties.org.quartz:
      threadPool.threadCount: 5
      jobStore:
        isClustered: true
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        tablePrefix: QRTZ_
      scheduler.instanceId: AUTO
      scheduler.instanceName: data-compliance-quartz

  profiles:
    group:
      test:
        - "stdout"
        - "local"
      dev:
        - "stdout"
        - "local"
        - "localstack"
        - "postgres"
      test-integration:
        - "stdout"
        - "local"
        - "hsqldb"
      test-dlq:
        - "stdout"
        - "local"
        - "localstack-test"
        - "hsqldb"
      message-integration:
        - "stdout"
        - "local"
        - "localstack-test"
        - "hsqldb"
      test-message-integration-with-review-period:
        - "stdout"
        - "local"
        - "localstack-test"
        - "hsqldb"

hmpps.sqs:
  queueAdminRole: ROLE_DATA_COMPLIANCE_QUEUE_ADMIN
  provider: aws

image.recognition:
  region: eu-west-2
  aws:
    collection.id: dps-offender-images
    face.similarity.threshold: 96.5

duplicate.detection:
  region: eu-west-1
  athena:
    database: ap_nomis_dedupe
    table: id_pairs_and_scores_test

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol_header: x-forwarded-proto

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'

  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

notify:
  templates:
    intention-to-delete: 7387f596-0a10-4a63-834c-7c5b34a5a934
    offender-data-cleansed: 9c8e7ce8-9429-48f5-9660-fbfa20473119

server.shutdown: graceful
