version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.11

executors:
  validator:
    docker:
      - image: cimg/openjdk:16.0
      - image: localstack/localstack:0.12.10
        environment:
          - SERVICES=sqs,sns
          - DEBUG=${DEBUG- }
          - DATA_DIR=/tmp/localstack/data
          - DOCKER_HOST=unix:///var/run/docker.sock
          - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
          - AWS_EXECUTION_ENV=True
          - DEFAULT_REGION=eu-west-2
          - TMPDIR=/private
    working_directory: ~/app

commands:
  run-tests:
    parameters:
      gradle-task:
        type: string
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run:
          command: ./gradlew <<parameters.gradle-task>>
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "16.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle
  test-integration:
    executor: validator
    steps:
      - run-tests:
          gradle-task: testIntegration
  test-message-integration:
    executor: validator
    steps:
      - run-tests:
          gradle-task: testMessageIntegration
  test-message-integration-with-review-period:
    executor: validator
    steps:
      - run-tests:
          gradle-task: testMessageIntegrationWithReviewPeriod
workflows:
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - test-integration:
          filters:
            tags:
              ignore: /.*/
      - test-message-integration:
          filters:
            tags:
              ignore: /.*/
      - test-message-integration-with-review-period:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only: main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
            - validate
            - helm_lint
            - test-integration
            - test-message-integration
            - test-message-integration-with-review-period
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - prison-data-compliance-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context:
            - hmpps-common-vars
            - prison-data-compliance-prod
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "58 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "54 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars


