version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.0.0
  owasp: entur/owasp@0.0.10

executors:
  validator:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      _JAVA_OPTIONS: -Xmx256m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-XX:+UseContainerSupport
    working_directory: ~/app

jobs:
  validate:
    executor: validator
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle

workflows:
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          snyk-fail-build: false
          snyk-scan: true
          snyk-threshold: high
          filters:
            branches:
              only: master
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - master
          requires:
            - validate
            - helm_lint
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context: prison-data-compliance-preprod
          requires:
            - request-preprod-approval
  scheduled:
    triggers:
      - schedule:
          cron: "0 8 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: validator
