INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS) VALUES ('CHILD_SEX_ABUSE', 'Child Sex Abuse Moratorium', FALSE);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS) VALUES ('HIGH_PROFILE', 'High Profile Offenders', FALSE);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS) VALUES ('LITIGATION_DISPUTE', 'Litigation/Dispute', FALSE);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS) VALUES ('LOOKED_AFTER_CHILDREN', 'Looked after children', FALSE);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS) VALUES ('MAPPA', 'MAPPA (Multi-Agency Public Protection Agreement)', FALSE);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS) VALUES ('FOI_SAR', 'Subject to FOI/SARs', FALSE);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS) VALUES ('OTHER', 'Other', TRUE);
