INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('CHILD_SEX_ABUSE', 'Child Sex Abuse Moratorium');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('HIGH_PROFILE', 'High Profile Offenders');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('LITIGATION_DISPUTE', 'Litigation/Dispute');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('LOOKED_AFTER_CHILDREN', 'Looked after children');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('MAPPA', 'Multi-Agency Public Protection Agreement');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('FOI_SAR', 'Subject to FOI/SARs');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('OTHER', 'Other');
