INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('CHILD_SEX_ABUSE', 'Child Sex Abuse Moratorium', FALSE, 0);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('HIGH_PROFILE', 'High Profile Offenders', FALSE, 1);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('LITIGATION_DISPUTE', 'Litigation/Dispute', FALSE, 2);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('LOOKED_AFTER_CHILDREN', 'Looked after children', FALSE, 3);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('MAPPA', 'MAPPA (Multi-Agency Public Protection Agreement)', FALSE, 4);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('FOI_SAR', 'Subject to FOI/SARs', FALSE, 5);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('UAL', 'UAL Recall on Licence', FALSE, 6);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('OTHER', 'Other', TRUE, 7);
