offender.retention:
  false.positive.duplicate.check.enabled: false
  image.duplicate.check.enabled: false
  mappa.check.enabled: true
  data.duplicate:
    id.check.enabled: true
    db.check.enabled: true
    ap.check.enabled: false

notify.enabled: false

deletion.grant.enabled: true
offender.deletion.review.required: false
image.recognition.deletion.enabled: true

