---
# Values here are the same across all environments
generic-service:
  nameOverride: dps-data-compliance

  image:
    repository: quay.io/hmpps/dps-data-compliance
    tag: app_version   # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    tlsSecretName: prison-data-compliance-cert
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    APP_DB_URL: "jdbc:postgresql://$(DB_ENDPOINT)/$(DB_NAME)?sslmode=verify-full"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    IMAGE_RECOGNITION_PROVIDER: aws
    DUPLICATE_DETECTION_PROVIDER: aws

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    dps-data-compliance:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      DPS_DATA_COMPLIANCE_CLIENT_ID: "DPS_DATA_COMPLIANCE_CLIENT_ID"
      DPS_DATA_COMPLIANCE_CLIENT_SECRET: "DPS_DATA_COMPLIANCE_CLIENT_SECRET"
      DUPLICATE_DETECTION_ATHENA_OUTPUT_LOCATION: "DUPLICATE_DETECTION_ATHENA_OUTPUT_LOCATION"
      DUPLICATE_DETECTION_ROLE_ARN: "DUPLICATE_DETECTION_ROLE_ARN"
      IMAGE_RECOGNITION_AWS_ACCESS_KEY_ID: "IMAGE_RECOGNITION_AWS_ACCESS_KEY_ID"
      IMAGE_RECOGNITION_AWS_SECRET_ACCESS_KEY: "IMAGE_RECOGNITION_AWS_SECRET_ACCESS_KEY"
      NOTIFY_API_KEY: "NOTIFY_API_KEY"
    dps-rds-instance-output:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DB_NAME: "database_name"
      DB_ENDPOINT: "rds_instance_endpoint"
    offender-events-topic:
      HMPPS_SQS_TOPICS_DATACOMPLIANCEEVENTS_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_TOPICS_DATACOMPLIANCEEVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_TOPICS_DATACOMPLIANCEEVENTS_ARN: "topic_arn"
    data-compliance-response-sqs:
      HMPPS_SQS_QUEUES_DATACOMPLIANCERESPONSE_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_DATACOMPLIANCERESPONSE_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_DATACOMPLIANCERESPONSE_QUEUE_NAME: "sqs_dc_resp_name"
    data-compliance-response-sqs-dl:
      HMPPS_SQS_QUEUES_DATACOMPLIANCERESPONSE_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_DATACOMPLIANCERESPONSE_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_DATACOMPLIANCERESPONSE_DLQ_NAME: "sqs_dc_resp_name"
    data-compliance-request-sqs:
      HMPPS_SQS_QUEUES_DATACOMPLIANCEREQUEST_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_DATACOMPLIANCEREQUEST_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_DATACOMPLIANCEREQUEST_QUEUE_NAME: "sqs_dc_req_name"
      HMPPS_SQS_QUEUES_DATACOMPLIANCEREQUEST_QUEUE_URL: "sqs_dc_req_url"
    data-compliance-request-sqs-dl:
      HMPPS_SQS_QUEUES_DATACOMPLIANCEREQUEST_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_DATACOMPLIANCEREQUEST_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_DATACOMPLIANCEREQUEST_DLQ_NAME: "sqs_dc_req_name"
    data-compliance-ap-user:
      DUPLICATE_DETECTION_AWS_ACCESS_KEY_ID: "data_compliance_ap_access_key_id"
      DUPLICATE_DETECTION_AWS_SECRET_ACCESS_KEY: "data_compliance_ap_secret_access_key"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: dps-data-compliance
