DROP TABLE IF EXISTS IMAGE_UPLOAD_BATCH;

CREATE TABLE IMAGE_UPLOAD_BATCH
(
  BATCH_ID                         BIGSERIAL       NOT NULL,
  UPLOAD_START_DATE_TIME           TIMESTAMP       NOT NULL,
  UPLOAD_END_DATE_TIME             TIMESTAMP,
  UPLOAD_COUNT                     BIGINT,

  CONSTRAINT IMG_UP_BATCH_PK PRIMARY KEY (BATCH_ID)
);

COMMENT ON TABLE IMAGE_UPLOAD_BATCH IS 'Records when a batch of images is uploaded to the image recognition service';

COMMENT ON COLUMN IMAGE_UPLOAD_BATCH.BATCH_ID IS 'Primary key id';
COMMENT ON COLUMN IMAGE_UPLOAD_BATCH.UPLOAD_START_DATE_TIME IS 'Timestamp of when this batch process started';
COMMENT ON COLUMN IMAGE_UPLOAD_BATCH.UPLOAD_END_DATE_TIME IS 'Timestamp of when this batch process ended';
COMMENT ON COLUMN IMAGE_UPLOAD_BATCH.UPLOAD_COUNT IS 'The number of faces successfully uploaded in this batch';

CREATE INDEX IMG_UP_BATCH_USDT_IDX ON IMAGE_UPLOAD_BATCH (UPLOAD_START_DATE_TIME);
CREATE INDEX IMG_UP_BATCH_UEDT_IDX ON IMAGE_UPLOAD_BATCH (UPLOAD_END_DATE_TIME);
