ALTER TABLE OFFENDER_DELETION_REFERRAL
    ADD AGENCY_LOCATION_ID VARCHAR( 10);

CREATE INDEX OFF_DEL_REF_ALI_IDX ON OFFENDER_DELETION_REFERRAL(AGENCY_LOCATION_ID);

COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.AGENCY_LOCATION_ID IS 'The last known agency location of the offender';