DROP TABLE IF EXISTS RETENTION_REASON_MANUAL;

CREATE TABLE RETENTION_REASON_MANUAL
(
  RETENTION_REASON_MANUAL_ID  BIGSERIAL       NOT NULL,
  RETENTION_CHECK_ID          BIGINT          NOT NULL,
  MANUAL_RETENTION_ID         BIGINT          NOT NULL,

  CONSTRAINT RET_REASON_MAN_PK      PRIMARY KEY (RETENTION_REASON_MANUAL_ID),
  CONSTRAINT RET_REASON_MAN_RCI_FK  FOREIGN KEY (RETENTION_CHECK_ID) REFERENCES RETENTION_CHECK(RETENTION_CHECK_ID),
  CONSTRAINT RET_REASON_MAN_MRI_FK  FOREIGN KEY (MANUAL_RETENTION_ID) REFERENCES MANUAL_RETENTION(MANUAL_RETENTION_ID)
);

COMMENT ON TABLE RETENTION_REASON_MANUAL IS 'Links the automatic retention reason to the manual retention of an offender';

COMMENT ON COLUMN RETENTION_REASON_MANUAL.RETENTION_REASON_MANUAL_ID IS 'Primary key id';
COMMENT ON COLUMN RETENTION_REASON_MANUAL.RETENTION_CHECK_ID IS 'The id of the parent retention check';
COMMENT ON COLUMN RETENTION_REASON_MANUAL.MANUAL_RETENTION_ID IS 'The id of the manual retention record';

CREATE INDEX RET_REA_MAN_RCI_IDX ON RETENTION_REASON_MANUAL(RETENTION_CHECK_ID);
CREATE INDEX RET_REA_MAN_MRI_IDX ON RETENTION_REASON_MANUAL(MANUAL_RETENTION_ID);
