UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 7 WHERE RETENTION_REASON_CODE_ID = 'OTHER';

INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('UAL', 'UAL Recall on Licence', FALSE, 6);
