DROP TABLE IF EXISTS RETENTION_REASON_DATA_DUPLICATE;

CREATE TABLE RETENTION_REASON_DATA_DUPLICATE
(
  RET_REASON_DATA_DUP_ID            BIGSERIAL       NOT NULL,
  RETENTION_CHECK_ID                BIGINT          NOT NULL,
  DATA_DUPLICATE_ID                 BIGINT          NOT NULL,

  CONSTRAINT RET_REA_DAT_DUP_PK     PRIMARY KEY (RET_REASON_DATA_DUP_ID),
  CONSTRAINT RET_REA_DAT_DUP_RCI_FK FOREIGN KEY (RETENTION_CHECK_ID) REFERENCES RETENTION_CHECK(RETENTION_CHECK_ID),
  CONSTRAINT RET_REA_DAT_DUP_DDI_FK FOREIGN KEY (DATA_DUPLICATE_ID) REFERENCES DATA_DUPLICATE(DATA_DUPLICATE_ID)
);

COMMENT ON TABLE RETENTION_REASON_DATA_DUPLICATE IS 'Links a retention reason to the image duplicate record';

COMMENT ON COLUMN RETENTION_REASON_DATA_DUPLICATE.RET_REASON_DATA_DUP_ID IS 'Primary key id';
COMMENT ON COLUMN RETENTION_REASON_DATA_DUPLICATE.RETENTION_CHECK_ID IS 'The id of the parent retention check';
COMMENT ON COLUMN RETENTION_REASON_DATA_DUPLICATE.DATA_DUPLICATE_ID IS 'The id of the data duplicate';

CREATE INDEX RET_REA_DAT_DUP_RCI_IDX ON RETENTION_REASON_DATA_DUPLICATE(RETENTION_CHECK_ID);
CREATE INDEX RET_REA_DAT_DUP_DDI_IDX ON RETENTION_REASON_DATA_DUPLICATE(DATA_DUPLICATE_ID);
