DROP TABLE IF EXISTS OFFENDER_NO_BOOKING_DELETION_BATCH;

CREATE TABLE OFFENDER_NO_BOOKING_DELETION_BATCH
(
  BATCH_ID                        BIGSERIAL       NOT NULL,
  REQUEST_DATE_TIME               TIMESTAMP       NOT NULL,
  REFERRAL_COMPLETION_DATE_TIME   TIMESTAMP,
  BATCH_TYPE                      VARCHAR(255)    NOT NULL,
  COMMENT_TEXT                    VARCHAR(4000),

  CONSTRAINT OFF_NO_BOOK_DEL_BAT_PK       PRIMARY KEY (BATCH_ID)
);

COMMENT ON TABLE OFFENDER_NO_BOOKING_DELETION_BATCH IS 'Tracks batched requests to delete offenders with no booking';

COMMENT ON COLUMN OFFENDER_NO_BOOKING_DELETION_BATCH.BATCH_ID IS 'Primary key id';
COMMENT ON COLUMN OFFENDER_NO_BOOKING_DELETION_BATCH.REQUEST_DATE_TIME IS 'The timestamp of the offender no booking deletion request';
COMMENT ON COLUMN OFFENDER_NO_BOOKING_DELETION_BATCH.REFERRAL_COMPLETION_DATE_TIME IS 'Confirmation timestamp of the deletion of the offenders with no booking data';
COMMENT ON COLUMN OFFENDER_NO_BOOKING_DELETION_BATCH.BATCH_TYPE IS 'The type of the offender with no booking deletion (e.g. SCHEDULED or AD_HOC)';
COMMENT ON COLUMN OFFENDER_NO_BOOKING_DELETION_BATCH.COMMENT_TEXT IS 'An explanation of why the deletion of the offender with no booking was required';

CREATE INDEX OFF_NO_BOOK_DEL_BAT_RDT_IDX ON OFFENDER_NO_BOOKING_DELETION_BATCH(REQUEST_DATE_TIME);
CREATE INDEX OFF_NO_BOOK_DEL_BAT_BT_IDX ON OFFENDER_NO_BOOKING_DELETION_BATCH(BATCH_TYPE);
