DROP TABLE IF EXISTS DECEASED_OFFENDER_DELETION_REFERRAL;

CREATE TABLE DECEASED_OFFENDER_DELETION_REFERRAL
(
  REFERRAL_ID                       BIGSERIAL       NOT NULL,
  BATCH_ID                          BIGINT          NOT NULL,
  OFFENDER_NO                       VARCHAR( 10)    NOT NULL,
  FIRST_NAME                        VARCHAR( 35),
  MIDDLE_NAME                       VARCHAR( 35),
  LAST_NAME                         VARCHAR( 35)    NOT NULL,
  BIRTH_DATE                        DATE,
  AGENCY_LOCATION_ID                VARCHAR( 10),
  DECEASED_DATE                     DATE,
  DELETION_DATE_TIME                TIMESTAMP       NOT NULL,

  CONSTRAINT DEC_OFF_DEL_REF_PK         PRIMARY KEY (REFERRAL_ID),
  CONSTRAINT DEC_OFF_DEL_REF_BAT_FK     FOREIGN KEY (BATCH_ID) REFERENCES DECEASED_OFFENDER_DELETION_BATCH (BATCH_ID)
);

COMMENT ON TABLE DECEASED_OFFENDER_DELETION_REFERRAL IS 'Records deceased offenders that have been referred for deletion';

COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.REFERRAL_ID IS 'Primary key id';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.BATCH_ID IS 'The ID of the deceased offender deletion batch that this referral is linked to';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.OFFENDER_NO IS 'The NOMS offender number';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.FIRST_NAME IS 'The first name of the root offender alias at time of referral';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.MIDDLE_NAME IS 'The middle name of the root offender alias at time of referral';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.LAST_NAME IS 'The last name of the root offender alias at time of referral';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.BIRTH_DATE IS 'The date of birth of the root offender alias at time of referral';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.AGENCY_LOCATION_ID IS 'The last known agency location of the offender';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.DECEASED_DATE IS 'The date of offender was registered as deceased on NOMIS';
COMMENT ON COLUMN DECEASED_OFFENDER_DELETION_REFERRAL.DELETION_DATE_TIME IS 'The UTC timstamp of when the deletion was completed';

CREATE INDEX DEC_OFF_DEL_REF_BI_IDX ON DECEASED_OFFENDER_DELETION_REFERRAL(BATCH_ID);
CREATE INDEX DEC_OFF_DEL_REF_ON_IDX ON DECEASED_OFFENDER_DELETION_REFERRAL(OFFENDER_NO);
CREATE INDEX DEC_OFF_DEL_REF_ALI_IDX ON DECEASED_OFFENDER_DELETION_REFERRAL(AGENCY_LOCATION_ID);
CREATE INDEX DEC_OFF_DEL_REF_REC_DT_IDX ON DECEASED_OFFENDER_DELETION_REFERRAL(DELETION_DATE_TIME);


