DROP TABLE IF EXISTS OFFENDER_DELETION_REFERRAL;

CREATE TABLE OFFENDER_DELETION_REFERRAL
(
  REFERRAL_ID                       BIGSERIAL       NOT NULL,
  BATCH_ID                          BIGINT          NOT NULL,
  OFFENDER_NO                       VARCHAR( 10)    NOT NULL,
  FIRST_NAME                        VARCHAR( 35),
  MIDDLE_NAME                       VARCHAR( 35),
  LAST_NAME                         VARCHAR( 35)    NOT NULL,
  BIRTH_DATE                        DATE,
  RECEIVED_DATE_TIME                TIMESTAMP       NOT NULL,

  CONSTRAINT OFF_DEL_REF_PK         PRIMARY KEY (REFERRAL_ID),
  CONSTRAINT OFF_DEL_REF_BAT_FK     FOREIGN KEY (BATCH_ID) REFERENCES OFFENDER_DELETION_BATCH (BATCH_ID)
);

COMMENT ON TABLE OFFENDER_DELETION_REFERRAL IS 'Records offenders that have been referred for deletion';

COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.REFERRAL_ID IS 'Primary key id';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.BATCH_ID IS 'The ID of the offender deletion batch that this referral is linked to';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.OFFENDER_NO IS 'The NOMS offender number';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.FIRST_NAME IS 'The first name of the root offender alias at time of referral';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.MIDDLE_NAME IS 'The middle name of the root offender alias at time of referral';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.LAST_NAME IS 'The last name of the root offender alias at time of referral';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.BIRTH_DATE IS 'The date of birth of the root offender alias at time of referral';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.RECEIVED_DATE_TIME IS 'The UTC timstamp of when the referral was received';

CREATE INDEX OFF_DEL_REF_BI_IDX ON OFFENDER_DELETION_REFERRAL(BATCH_ID);
CREATE INDEX OFF_DEL_REF_ON_IDX ON OFFENDER_DELETION_REFERRAL(OFFENDER_NO);
CREATE INDEX OFF_DEL_REF_REC_DT_IDX ON OFFENDER_DELETION_REFERRAL(RECEIVED_DATE_TIME);
