DROP TABLE IF EXISTS RETENTION_REASON_CODE;

CREATE TABLE RETENTION_REASON_CODE
(
  RETENTION_REASON_CODE_ID         VARCHAR(255)    NOT NULL,
  DISPLAY_NAME                     VARCHAR(255)    NOT NULL,
  ALLOW_REASON_DETAILS             BOOLEAN         NOT NULL,
  DISPLAY_ORDER                    INTEGER         NOT NULL,

  CONSTRAINT RET_REASON_CODE_PK    PRIMARY KEY (RETENTION_REASON_CODE_ID)
);

COMMENT ON TABLE RETENTION_REASON_CODE IS 'List of possible offender record retention reasons';

COMMENT ON COLUMN RETENTION_REASON_CODE.RETENTION_REASON_CODE_ID IS 'Primary key id';
COMMENT ON COLUMN RETENTION_REASON_CODE.DISPLAY_NAME IS 'Text used to display in UI';
COMMENT ON COLUMN RETENTION_REASON_CODE.ALLOW_REASON_DETAILS  IS 'Indication of whether the end user is allowed to comment on the reason they have provided';
COMMENT ON COLUMN RETENTION_REASON_CODE.DISPLAY_ORDER IS 'Order in which the reasons are displayed to the end user';

INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('CHILD_SEX_ABUSE', 'Child Sex Abuse Moratorium', FALSE, 0);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('HIGH_PROFILE', 'High Profile Offenders', FALSE, 1);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('LITIGATION_DISPUTE', 'Litigation/Dispute', FALSE, 2);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('LOOKED_AFTER_CHILDREN', 'Looked after children', FALSE, 3);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('MAPPA', 'MAPPA (Multi-Agency Public Protection Agreement)', FALSE, 4);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('FOI_SAR', 'Subject to FOI/SAR', FALSE, 5);
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME, ALLOW_REASON_DETAILS, DISPLAY_ORDER) VALUES ('OTHER', 'Other', TRUE, 6);
