DROP TABLE IF EXISTS MANUAL_RETENTION;

CREATE TABLE MANUAL_RETENTION
(
  MANUAL_RETENTION_ID           BIGSERIAL       NOT NULL,
  OFFENDER_NO                   VARCHAR( 10)    NOT NULL,
  RETENTION_DATE_TIME           TIMESTAMP       NOT NULL,
  USER_ID                       VARCHAR(32)     NOT NULL,
  RETENTION_VERSION             INTEGER         NOT NULL,

  CONSTRAINT MAN_RET_PK         PRIMARY KEY (MANUAL_RETENTION_ID),
  CONSTRAINT MAN_RET_OV_UNIQUE  UNIQUE (OFFENDER_NO, RETENTION_VERSION)
);

COMMENT ON TABLE MANUAL_RETENTION IS 'Records a new/updated request by a member of staff to retain an offender record';

COMMENT ON COLUMN MANUAL_RETENTION.MANUAL_RETENTION_ID IS 'Primary key id';
COMMENT ON COLUMN MANUAL_RETENTION.OFFENDER_NO IS 'The NOMS offender number';
COMMENT ON COLUMN MANUAL_RETENTION.RETENTION_DATE_TIME IS 'The timestamp of this retention creation/update';
COMMENT ON COLUMN MANUAL_RETENTION.USER_ID IS 'ID of the user who created the record';
COMMENT ON COLUMN MANUAL_RETENTION.RETENTION_VERSION IS 'Version number of the offender retention record';

CREATE INDEX MAN_RET_ON_IDX ON MANUAL_RETENTION(OFFENDER_NO);
