DROP TABLE IF EXISTS MANUAL_RETENTION_REASON;

CREATE TABLE MANUAL_RETENTION_REASON
(
  MANUAL_RETENTION_REASON_ID         BIGSERIAL       NOT NULL,
  MANUAL_RETENTION_ID                BIGINT          NOT NULL,
  RETENTION_REASON_CODE_ID           VARCHAR(255)    NOT NULL,
  REASON_DETAILS                     VARCHAR(4000),

  CONSTRAINT MAN_RET_REASON_PK       PRIMARY KEY (MANUAL_RETENTION_REASON_ID),
  CONSTRAINT MAN_RET_REASON_MRI_FK   FOREIGN KEY (MANUAL_RETENTION_ID) REFERENCES MANUAL_RETENTION(MANUAL_RETENTION_ID),
  CONSTRAINT MAN_RET_REASON_RRCI_FK  FOREIGN KEY (RETENTION_REASON_CODE_ID) REFERENCES RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID)
);

COMMENT ON TABLE MANUAL_RETENTION_REASON IS 'Lists reasons why an offender record has been marked for retention';

COMMENT ON COLUMN MANUAL_RETENTION_REASON.MANUAL_RETENTION_REASON_ID IS 'Primary key id';
COMMENT ON COLUMN MANUAL_RETENTION_REASON.MANUAL_RETENTION_ID IS 'ID of the manual retention record that this reason is linked to';
COMMENT ON COLUMN MANUAL_RETENTION_REASON.RETENTION_REASON_CODE_ID IS 'The retention reason code describing this retention reason';
COMMENT ON COLUMN MANUAL_RETENTION_REASON.REASON_DETAILS IS 'Further details on the retention reason';

CREATE INDEX MAN_RET_REASON_MRI_IDX ON MANUAL_RETENTION_REASON(MANUAL_RETENTION_ID);
CREATE INDEX MAN_RET_REASON_RRCI_IDX ON MANUAL_RETENTION_REASON(RETENTION_REASON_CODE_ID);
