DROP TABLE IF EXISTS RETENTION_REASON;

CREATE TABLE RETENTION_REASON
(
  RETENTION_REASON_ID     BIGSERIAL       NOT NULL,
  RESOLUTION_ID           BIGINT          NOT NULL,
  MANUAL_RETENTION_ID     BIGINT,

  CONSTRAINT RET_REASON_PK       PRIMARY KEY (RETENTION_REASON_ID),
  CONSTRAINT RET_REASON_RES_FK   FOREIGN KEY (RESOLUTION_ID) REFERENCES REFERRAL_RESOLUTION(RESOLUTION_ID)
);

COMMENT ON TABLE RETENTION_REASON IS 'Represents the reason(s) why an offender record should be retained';

COMMENT ON COLUMN RETENTION_REASON.RETENTION_REASON_ID IS 'Primary key id';
COMMENT ON COLUMN RETENTION_REASON.RESOLUTION_ID IS 'The id of the referral resolution';
COMMENT ON COLUMN RETENTION_REASON.MANUAL_RETENTION_ID IS 'The id of the manual retention record';
