DROP TABLE IF EXISTS RETENTION_REASON_MANUAL;

CREATE TABLE RETENTION_REASON_MANUAL
(
  RETENTION_REASON_MANUAL_ID  BIGSERIAL       NOT NULL,
  RETENTION_REASON_ID         BIGINT          NOT NULL,
  MANUAL_RETENTION_ID         BIGINT          NOT NULL,

  CONSTRAINT RET_REASON_MAN_PK      PRIMARY KEY (RETENTION_REASON_MANUAL_ID),
  CONSTRAINT RET_REASON_MAN_RRI_FK  FOREIGN KEY (RETENTION_REASON_ID) REFERENCES RETENTION_REASON(RETENTION_REASON_ID),
  CONSTRAINT RET_REASON_MAN_MRI_FK  FOREIGN KEY (MANUAL_RETENTION_ID) REFERENCES MANUAL_RETENTION(MANUAL_RETENTION_ID)
);

COMMENT ON TABLE RETENTION_REASON_MANUAL IS 'Links the automatic retention reason to the manual retention of an offender';

COMMENT ON COLUMN RETENTION_REASON_MANUAL.RETENTION_REASON_MANUAL_ID IS 'Primary key id';
COMMENT ON COLUMN RETENTION_REASON_MANUAL.RETENTION_REASON_ID IS 'The id of the parent retention reason';
COMMENT ON COLUMN RETENTION_REASON_MANUAL.MANUAL_RETENTION_ID IS 'The id of the manual retention record';
