ALTER TABLE OFFENDER_DELETION_REFERRAL ADD BATCH_ID BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE OFFENDER_DELETION_REFERRAL ADD CONSTRAINT OFF_DEL_REF_BAT_FK FOREIGN KEY (BATCH_ID) REFERENCES OFFENDER_DELETION_BATCH (BATCH_ID);
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.BATCH_ID IS 'The ID of the offender deletion batch that this referral is linked to';
