ALTER TABLE RETENTION_REASON_CODE ADD ALLOW_REASON_DETAILS BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE RETENTION_REASON_CODE ADD DISPLAY_ORDER INTEGER DEFAULT 0 NOT NULL;
COMMENT ON COLUMN RETENTION_REASON_CODE.ALLOW_REASON_DETAILS  IS 'Indication of whether the end user is allowed to comment on the reason they have provided';
COMMENT ON COLUMN RETENTION_REASON_CODE.DISPLAY_ORDER IS 'Order in which the reasons are displayed to the end user';

UPDATE RETENTION_REASON_CODE SET ALLOW_REASON_DETAILS = TRUE WHERE RETENTION_REASON_CODE_ID = 'OTHER';
UPDATE RETENTION_REASON_CODE SET DISPLAY_NAME = 'MAPPA (Multi-Agency Public Protection Agreement)' WHERE RETENTION_REASON_CODE_ID = 'MAPPA';
UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 0 WHERE RETENTION_REASON_CODE_ID = 'CHILD_SEX_ABUSE';
UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 1 WHERE RETENTION_REASON_CODE_ID = 'HIGH_PROFILE';
UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 2 WHERE RETENTION_REASON_CODE_ID = 'LITIGATION_DISPUTE';
UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 3 WHERE RETENTION_REASON_CODE_ID = 'LOOKED_AFTER_CHILDREN';
UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 4 WHERE RETENTION_REASON_CODE_ID = 'MAPPA';
UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 5 WHERE RETENTION_REASON_CODE_ID = 'FOI_SAR';
UPDATE RETENTION_REASON_CODE SET DISPLAY_ORDER = 6 WHERE RETENTION_REASON_CODE_ID = 'OTHER';
