DROP TABLE IF EXISTS OFFENDER_IMAGE_UPLOAD;

CREATE TABLE OFFENDER_IMAGE_UPLOAD
(
  UPLOAD_ID                         BIGSERIAL       NOT NULL,
  OFFENDER_NO                       VARCHAR( 10)    NOT NULL,
  OFFENDER_IMAGE_ID                 BIGINT          NOT NULL,
  FACE_ID                           VARCHAR( 255)   NOT NULL,
  UPLOAD_DATE_TIME                  TIMESTAMP       NOT NULL,
  BATCH_ID                          BIGINT          NOT NULL,

  CONSTRAINT OFF_IMG_UP_PK          PRIMARY KEY (UPLOAD_ID),
  CONSTRAINT OFF_IMG_UP_UNIQUE      UNIQUE (OFFENDER_NO, OFFENDER_IMAGE_ID),
  CONSTRAINT OFF_IMG_UP_BATCH_FK    FOREIGN KEY (BATCH_ID) REFERENCES IMAGE_UPLOAD_BATCH(BATCH_ID)
);

COMMENT ON TABLE OFFENDER_IMAGE_UPLOAD IS 'Records details of a successful image upload to the image recognition service';

COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.UPLOAD_ID IS 'Primary key id';
COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.OFFENDER_NO IS 'The NOMS offender number';
COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.OFFENDER_IMAGE_ID IS 'The NOMS offender image id';
COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.FACE_ID IS 'The image recognition service id for the indexed face';
COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.UPLOAD_DATE_TIME IS 'The timestamp of when the upload completed';
COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.BATCH_ID IS 'The id of the batch of uploads in which this upload belongs';

CREATE INDEX OFF_IMG_UP_ON_IDX ON OFFENDER_IMAGE_UPLOAD(OFFENDER_NO);
CREATE INDEX OFF_IMG_UP_OII_IDX ON OFFENDER_IMAGE_UPLOAD(OFFENDER_IMAGE_ID);
CREATE INDEX OFF_IMG_UP_FI_IDX ON OFFENDER_IMAGE_UPLOAD(FACE_ID);
CREATE INDEX OFF_IMG_UP_UDT_IDX ON OFFENDER_IMAGE_UPLOAD(UPLOAD_DATE_TIME);
CREATE INDEX OFF_IMG_UP_BI_IDX ON OFFENDER_IMAGE_UPLOAD(BATCH_ID);
