ALTER TABLE RETENTION_REASON ADD REASON_CODE VARCHAR(255) DEFAULT 'MANUAL_RETENTION' NOT NULL;
COMMENT ON COLUMN RETENTION_REASON.REASON_CODE IS 'An enumerated reason type summarising why an offender has been automatically retained';
ALTER TABLE RETENTION_REASON DROP COLUMN MANUAL_RETENTION_ID;
