ALTER TABLE RETENTION_REASON_CODE ADD ALLOW_REASON_DETAILS BOOLEAN DEFAULT FALSE NOT NULL;
COMMENT ON COLUMN RETENTION_REASON_CODE.ALLOW_REASON_DETAILS  IS 'Indication of whether the end user is allowed to comment on the reason they have provided';

UPDATE RETENTION_REASON_CODE SET ALLOW_REASON_DETAILS = TRUE WHERE RETENTION_REASON_CODE_ID = 'OTHER';
UPDATE RETENTION_REASON_CODE SET DISPLAY_NAME = 'MAPPA (Multi-Agency Public Protection Agreement)' WHERE RETENTION_REASON_CODE_ID = 'MAPPA';

