ALTER TABLE RETENTION_REASON RENAME TO RETENTION_CHECK;
ALTER TABLE RETENTION_CHECK RENAME COLUMN RETENTION_REASON_ID TO RETENTION_CHECK_ID;
ALTER TABLE RETENTION_CHECK RENAME COLUMN REASON_CODE TO CHECK_TYPE;
ALTER TABLE RETENTION_CHECK ADD CHECK_STATUS VARCHAR(255) DEFAULT 'RETENTION_REQUIRED' NOT NULL;
COMMENT ON COLUMN RETENTION_CHECK.CHECK_TYPE IS 'An enumerated retention check type';
COMMENT ON COLUMN RETENTION_CHECK.CHECK_STATUS IS 'An enumerated status for the retention check';

ALTER TABLE RETENTION_REASON_MANUAL RENAME COLUMN RETENTION_REASON_ID TO RETENTION_CHECK_ID;
ALTER TABLE RETENTION_REASON_DATA_DUPLICATE RENAME COLUMN RETENTION_REASON_ID TO RETENTION_CHECK_ID;
ALTER TABLE RETENTION_REASON_IMAGE_DUPLICATE RENAME COLUMN RETENTION_REASON_ID TO RETENTION_CHECK_ID;
