CREATE INDEX OFF_DEL_REF_BI_IDX ON OFFENDER_DELETION_REFERRAL(BATCH_ID);
CREATE INDEX REF_RES_RI_IDX ON REFERRAL_RESOLUTION(REFERRAL_ID);
CREATE INDEX RET_REASON_RI_IDX ON RETENTION_REASON(RESOLUTION_ID);
CREATE INDEX RET_REASON_MAN_RRI_IDX ON RETENTION_REASON_MANUAL(RETENTION_REASON_ID);
CREATE INDEX RET_REASON_MAN_MRI_IDX ON RETENTION_REASON_MANUAL(MANUAL_RETENTION_ID);
CREATE INDEX MAN_RET_REASON_MRI_IDX ON MANUAL_RETENTION_REASON(MANUAL_RETENTION_ID);
CREATE INDEX MAN_RET_REASON_RRCI_IDX ON MANUAL_RETENTION_REASON(RETENTION_REASON_CODE_ID);
