DROP TABLE IF EXISTS DATA_DUPLICATE;

CREATE TABLE DATA_DUPLICATE
(
  DATA_DUPLICATE_ID               BIGSERIAL       NOT NULL,
  REFERENCE_OFFENDER_NO           VARCHAR( 10)    NOT NULL,
  DUPLICATE_OFFENDER_NO           VARCHAR( 10)    NOT NULL,
  DETECTION_DATE_TIME             TIMESTAMP       NOT NULL,

  CONSTRAINT DAT_DUP_PK           PRIMARY KEY (DATA_DUPLICATE_ID)
);

COMMENT ON TABLE DATA_DUPLICATE IS 'Records links between offenders where, based on the data held in NOMIS, they are thought to be the same person';

COMMENT ON COLUMN DATA_DUPLICATE.DATA_DUPLICATE_ID IS 'Primary key id';
COMMENT ON COLUMN DATA_DUPLICATE.REFERENCE_OFFENDER_NO IS 'The NOMS offender number of the first offender in the pair';
COMMENT ON COLUMN DATA_DUPLICATE.DUPLICATE_OFFENDER_NO IS 'The NOMS offender number of the second offender in the pair';
COMMENT ON COLUMN IMAGE_DUPLICATE.DETECTION_DATE_TIME IS 'The timestamp of when the duplicate was detected';

CREATE INDEX DAT_DUP_RON_IDX ON DATA_DUPLICATE(REFERENCE_OFFENDER_NO);
CREATE INDEX DAT_DUP_DON_IDX ON DATA_DUPLICATE(DUPLICATE_OFFENDER_NO);
