ALTER TABLE OFFENDER_DELETION_BATCH ALTER COLUMN WINDOW_START_DATE_TIME DROP NOT NULL;
ALTER TABLE OFFENDER_DELETION_BATCH ALTER COLUMN WINDOW_END_DATE_TIME DROP NOT NULL;

ALTER TABLE OFFENDER_DELETION_BATCH ADD BATCH_TYPE VARCHAR(255) DEFAULT 'SCHEDULED' NOT NULL;
COMMENT ON COLUMN OFFENDER_DELETION_BATCH.BATCH_TYPE IS 'The type of the offender deletion (e.g. SCHEDULED or ADHOC)';

ALTER TABLE OFFENDER_DELETION_BATCH ADD COMMENT_TEXT VARCHAR(4000);
COMMENT ON COLUMN OFFENDER_DELETION_BATCH.COMMENT_TEXT IS 'An explanation of why the deletion was required';
