ALTER TABLE OFFENDER_IMAGE_UPLOAD ADD UPLOAD_ERROR_REASON VARCHAR( 255);

COMMENT ON TABLE OFFENDER_IMAGE_UPLOAD IS 'Records details of an attempted image upload to the image recognition service';

COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.UPLOAD_ERROR_REASON IS 'Reason why an attempted image upload did not produced indexed face record';

CREATE INDEX OFF_IMG_UP_UER_IDX ON OFFENDER_IMAGE_UPLOAD(UPLOAD_ERROR_REASON);

ALTER TABLE OFFENDER_IMAGE_UPLOAD ALTER COLUMN FACE_ID DROP NOT NULL;

