ALTER TABLE OFFENDER_IMAGE_UPLOAD ADD UPLOAD_STATUS VARCHAR(255) DEFAULT 'SUCCESS' NOT NULL;
COMMENT ON COLUMN OFFENDER_IMAGE_UPLOAD.UPLOAD_STATUS IS 'Enumerated status for the image upload';
UPDATE OFFENDER_IMAGE_UPLOAD SET UPLOAD_STATUS = 'ERROR' WHERE UPLOAD_ERROR_REASON IS NOT NULL;
