DROP TABLE IF EXISTS REFERRED_OFFENDER_BOOKING;

CREATE TABLE REFERRED_OFFENDER_BOOKING
(
  REFERRED_OFFENDER_BOOKING_ID        BIGSERIAL       NOT NULL,
  OFFENDER_ID                         NUMERIC(10, 0)  NOT NULL,
  OFFENDER_BOOK_ID                    NUMERIC(10, 0)  NOT NULL,
  REFERRAL_ID                         BIGINT          NOT NULL,

  CONSTRAINT REF_OFF_BOOK_PK          PRIMARY KEY (REFERRED_OFFENDER_BOOKING_ID),
  CONSTRAINT REF_OFF_BOOK_REFERRAL_FK FOREIGN KEY (REFERRAL_ID) REFERENCES OFFENDER_DELETION_REFERRAL(REFERRAL_ID)
);

COMMENT ON TABLE REFERRED_OFFENDER_BOOKING IS 'Table to store booking ids for a referred offender';

COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.REFERRED_OFFENDER_BOOKING_ID IS 'Primary key id';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.OFFENDER_ID IS 'This is the primary key in NOMIS for the OFFENDERS table';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.OFFENDER_BOOK_ID IS 'This is the primary key in NOMIS for the OFFENDER_BOOKINGS table';
COMMENT ON COLUMN OFFENDER_DELETION_REFERRAL.REFERRAL_ID IS 'This links the ids here to the referred offender';

CREATE INDEX REF_OFF_BOOK_RI_IDX ON REFERRED_OFFENDER_BOOKING(REFERRAL_ID);
