DROP TABLE IF EXISTS RETENTION_REASON_CODE;

CREATE TABLE RETENTION_REASON_CODE
(
  RETENTION_REASON_CODE_ID         VARCHAR(255)    NOT NULL,
  DISPLAY_NAME                     VARCHAR(255)    NOT NULL,

  CONSTRAINT RET_REASON_CODE_PK    PRIMARY KEY (RETENTION_REASON_CODE_ID)
);

COMMENT ON TABLE RETENTION_REASON_CODE IS 'List of possible offender record retention reasons';

COMMENT ON COLUMN RETENTION_REASON_CODE.RETENTION_REASON_CODE_ID IS 'Primary key id';
COMMENT ON COLUMN RETENTION_REASON_CODE.DISPLAY_NAME IS 'Text used to display in UI';

INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('CHILD_SEX_ABUSE', 'Child Sex Abuse Moratorium');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('HIGH_PROFILE', 'High Profile Offenders');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('LITIGATION_DISPUTE', 'Litigation/Dispute');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('LOOKED_AFTER_CHILDREN', 'Looked after children');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('MAPPA', 'Multi-Agency Public Protection Agreement');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('FOI_SAR', 'Subject to FOI/SARs');
INSERT INTO RETENTION_REASON_CODE(RETENTION_REASON_CODE_ID, DISPLAY_NAME) VALUES ('OTHER', 'Other');
