ALTER TABLE MANUAL_RETENTION ADD RETENTION_VERSION INTEGER NOT NULL;
COMMENT ON COLUMN MANUAL_RETENTION.RETENTION_VERSION IS 'Version number of the offender retention record';
ALTER TABLE MANUAL_RETENTION ADD CONSTRAINT MAN_RET_OV_UNIQUE UNIQUE (OFFENDER_NO, RETENTION_VERSION);

ALTER TABLE MANUAL_RETENTION DROP COLUMN STAFF_ID;
ALTER TABLE MANUAL_RETENTION ADD USER_ID VARCHAR(32) NOT NULL;
COMMENT ON COLUMN MANUAL_RETENTION.USER_ID IS 'ID of the user who created the record';

