apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  DPS_DATA_COMPLIANCE_CLIENT_ID: {{ .Values.secrets.DPS_DATA_COMPLIANCE_CLIENT_ID | b64enc | quote }}
  DPS_DATA_COMPLIANCE_CLIENT_SECRET: {{ .Values.secrets.DPS_DATA_COMPLIANCE_CLIENT_SECRET | b64enc | quote }}
  IMAGE_RECOGNITION_AWS_ACCESS_KEY_ID: {{ .Values.secrets.IMAGE_RECOGNITION_AWS_ACCESS_KEY_ID | b64enc | quote }}
  IMAGE_RECOGNITION_AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.IMAGE_RECOGNITION_AWS_SECRET_ACCESS_KEY | b64enc | quote }}
